### ISSUE TITLE
Login js example wrong

### ISSUE THREAD

**Issue by ireinhart** [galenframework/galenframework.com#16]
The "Exception" should be an "Error" at http://galenframework.com/docs/reference-galen-test-suite-syntax/#PageActionsSeleniumInteraction
or in this line
https://github.com/galenframework/galenframework.com/blob/master/db/docs/reference-galen-test-suite-syntax.blogix#L326

I got the following error:
org.mozilla.javascript.EcmaError: ReferenceError: "Exception" is not defined. (/app/tests/galen/scripts/checkConsoleLog.js#19)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3689)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3667)
        at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3752)

**Comment by ishubin** [comment]
Oops, thanks for notifying! I will update it
